### PR TITLE
Add modern image scales.

### PR DESCRIPTION
**Pull request by tisto**

### CODE REVIEW

**Comment by sneridagh** [comment]
@tisto I tweaked it a bit, to make this optional, already been bitten by this several times.

**Comment by tisto** [comment]
@sneridagh do you see a risk in applying those image sizes in existing projects? We could as well do a breaking release.

**Comment by sneridagh** [comment]
@tisto I would initially make it opt-in, present it on Tuesday to the @plone/volto-team then make a breaking making it mandatory. Also, there is a initiative by @tiberiuichim for improve the scales and image conversions that we will discuss on Tuesday too.

**Comment by sneridagh** [comment]
@plone/volto-team These are the scales that we mentioned on the last meeting:

        <element>icon 32:32</element>
        <element>tile 64:64</element>
        <element>thumb 128:128</element>
        <element>mini 200:65536</element>
        <element>preview 400:65536</element>
        <element>teaser 600:65536</element>
        <element>large 800:65536</element>
        <element>larger 1000:65536</element>
        <element>great 1200:65536</element>
        <element>huge 1600:65536</element>     

they will override Plone's existing ones, if you want to define your own, then you should apply yours after applying this profile.

What do you think? Do you feel that there's some scales you are using missing?

I would not bloat it much more anyways, since the scales are created on save (all of them) this is something that Plone itself should fix at some point. Also, if we move from using Plone scales will be much better, but as a first step, we should define them.

**Pull request merged**
